[tool.poetry]
name = "unox"
version = "0.1.0"
description = "Use machine learning to make NOX predictions"
authors = ["Mikhail Schee"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
matplotlib = ">=3.4.3"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
